/** @format */

export const products = [
  {
    productName: "Apple AirPods",
    productDesc:
      "Sleek, wireless design that seamlessly integrates with your Apple devices for a magical listening experience",
    productCategory: "",
    productId: "001",
    productBrand: "Apple",
    productColor: "black",
    productPrice: "100",
    productRating: "3",
    productImg: "/images/airpod_5_apple_black.png",
  },
  {
    productName: "Oraimo AirBuds 4",
    productDesc:
      " Environmental Noise Cancellation ensures clear communication during calls, even in windy or noisy conditions",
    productCategory: "",
    productId: "002",
    productBrand: "Oraimo",
    productColor: "black",
    productPrice: "100",
    productRating: "4",
    productImg: "/images/earbud_1_oraimo_black.jpeg",
  },
  {
    productName: "Apple EarPods",
    productDesc:
      "Effortless pairing and a stable connection let you enjoy your music without interruptions",
    productCategory: "",
    productId: "003",
    productBrand: "Apple",
    productColor: "white",
    productPrice: "200",
    productRating: "5",
    productImg: "/images/earbud_3_apple_white.jpeg",
  },
  {
    productName: "Apple EarPods",
    productDesc:
      "Effortless pairing and a stable connection let you enjoy your music without interruptions",
    productCategory: "",
    productId: "004",
    productBrand: "Apple",
    productColor: "black",
    productPrice: "70",
    productRating: "5",
    productImg: "/images/earbud_4_apple_black.jpeg",
  },
  {
    productName: "Oraimo AirBuds 3",
    productDesc:
      "Effortless pairing and a stable connection let you enjoy your music without interruptions",
    productCategory: "",
    productId: "005",
    productBrand: "Oraimo",
    productColor: "black",
    productPrice: "50",
    productRating: "2.5",
    productImg: "/images/earpod_2_oraimo_black.jpg",
  },
  {
    productName: "Blackview AirBuds ",
    productDesc:
      "Effortless pairing and a stable connection let you enjoy your music without interruptions",
    productCategory: "",
    productId: "006",
    productBrand: "Blackview",
    productColor: "black",
    productPrice: "80",
    productRating: "4",
    productImg: "/images/earpod_5_blackview_black.png",
  },
  {
    productName: "AirBuds 4 Pro",
    productDesc:
      "Effortless pairing and a stable connection let you enjoy your music without interruptions",
    productCategory: "",
    productId: "007",
    productBrand: "Blackview",
    productColor: "black",
    productPrice: "200",
    productRating: "3",
    productImg: "/images/earpod_6_blackview_black.jpg",
  },
  {
    productName: "Bluetooth 5.0 Headphone",
    productDesc:
      "High-fidelity audio with exceptional clarity and powerful bass for an immersive listening experience.",
    productCategory: "",
    productId: "008",
    productBrand: "Oraimo",
    productColor: "other",
    productPrice: "150",
    productRating: "4",
    productImg: "/images/headset_1_oraimo_green.png",
  },
  {
    productName: "Sound Play",
    productDesc:
      " High-fidelity drivers deliver crisp highs, rich mids, and powerful bass for an enjoyable listening experience",
    productCategory: "",
    productId: "009",
    productBrand: "Apple",
    productColor: "white",
    productPrice: "150",
    productRating: "2.5",
    productImg: "/images/headset_2_apple_white.jpg",
  },
  {
    productName: "VT USD-Headset",
    productDesc:
      "Effortless pairing and a stable connection let you enjoy your music without interruptions",
    productCategory: "",
    productId: "010",
    productBrand: "Blackview",
    productColor: "white",
    productPrice: "80",
    productRating: "1",
    productImg: "/images/headset_2_blackview_white.jpg",
  },
  {
    productName: "Bluetooth 5.0 Headphone",
    productDesc:
      " High-fidelity drivers deliver crisp highs, rich mids, and powerful bass for an enjoyable listening experience",
    productCategory: "",
    productId: "011",
    productBrand: "Oraimo",
    productColor: "black",
    productPrice: "100",
    productRating: "2",
    productImg: "/images/headset_2_oraimo_black.jpeg",
  },
  {
    productName: "Bluetooth 3.0 Headphone",
    productDesc:
      " High-fidelity drivers deliver crisp highs, rich mids, and powerful bass for an enjoyable listening experience",
    productCategory: "",
    productId: "012",
    productBrand: "Blackview",
    productColor: "black",
    productPrice: "100",
    productRating: "3",
    productImg: "/images/headset_3_oraimo_black.jpg",
  },
  {
    productName: "Shure Sound Max",
    productDesc:
      " High-fidelity drivers deliver crisp highs, rich mids, and powerful bass for an enjoyable listening experience",
    productCategory: "",
    productId: "013",
    productBrand: "Oraimo",
    productColor: "black",
    productPrice: "100",
    productRating: "4",
    productImg: "/images/headset_3_oraimo_black.jpg",
  },
  {
    productName: "Bluetooth 5.0 Studio",
    productDesc:
      " High-fidelity drivers deliver crisp highs, rich mids, and powerful bass for an enjoyable listening experience",
    productCategory: "",
    productId: "014",
    productBrand: "Apple",
    productColor: "other",
    productPrice: "200",
    productRating: "3.5",
    productImg: "/images/headset_4_apple_gold.jpg",
  },
  {
    productName: "Blackview Headphone Pro",
    productDesc:
      " High-fidelity drivers deliver crisp highs, rich mids, and powerful bass for an enjoyable listening experience",
    productCategory: "",
    productId: "015",
    productBrand: "Blackview",
    productColor: "other",
    productPrice: "200",
    productRating: "4.5",
    productImg: "/images/headset_5_blackview_blue.png",
  },

  {
    productName: "Razwer Kitty V2 Pro",
    productDesc:
      " High-fidelity drivers deliver crisp highs, rich mids, and powerful bass for an enjoyable listening experience",
    productCategory: "",
    productId: "016",
    productBrand: "Blackview",
    productColor: "other",
    productPrice: "170",
    productRating: "3",
    productImg: "/images/headset_6_blackview_pink.jpeg",
  },

  {
    productName: "Apple Soundcity Max",
    productDesc:
      " High-fidelity drivers deliver crisp highs, rich mids, and powerful bass for an enjoyable listening experience",
    productCategory: "",
    productId: "017",
    productBrand: "Apple",
    productColor: "white",
    productPrice: "180",
    productRating: "4",
    productImg: "/images/headset_7_apple_white.jpeg",
  },
  {
    productName: "Blackview Headphone Pro",
    productDesc:
      " High-fidelity drivers deliver crisp highs, rich mids, and powerful bass for an enjoyable listening experience",
    productCategory: "",
    productId: "018",
    productBrand: "Blackview",
    productColor: "other",
    productPrice: "160",
    productRating: "3.5",
    productImg: "/images/headset_7_apple_white.jpeg",
  },
];
