/** @format */

export const products = [
  {
    productName: "Apple AirPods",
    productDesc:
      "Sleek, wireless design that seamlessly integrates with your Apple devices for a magical listening experience",
    productCategory: "",
    productId: "001",
    productBrand: "Apple",
    productColor: "black",
    productPrice: "100",
    productRating: "4",
    productImg: "./../IMAGES/airpod-5-apple-black.png",
  },
  {
    productName: "Oraimo AirBuds 4",
    productDesc:
      " Environmental Noise Cancellation ensures clear communication during calls, even in windy or noisy conditions",
    productCategory: "",
    productId: "002",
    productBrand: "Oraimo",
    productColor: "black",
    productPrice: "100",
    productRating: "4",
    productImg: "./../IMAGES/earbud-1-oraimo-black.jpeg",
  },
  {
    productName: "Apple EarPods",
    productDesc:
      "Effortless pairing and a stable connection let you enjoy your music without interruptions",
    productCategory: "",
    productId: "003",
    productBrand: "Apple",
    productColor: "white",
    productPrice: "200",
    productRating: "4",
    productImg: "./../IMAGES/earbud-3-apple-white.jpeg",
  },
  {
    productName: "Apple EarPods",
    productDesc:
      "Effortless pairing and a stable connection let you enjoy your music without interruptions",
    productCategory: "",
    productId: "004",
    productBrand: "Apple",
    productColor: "black",
    productPrice: "70",
    productRating: "4",
    productImg: "./../IMAGES/earbud-4-apple-black.jpeg",
  },
  {
    productName: "Oraimo AirBuds 3",
    productDesc:
      "Effortless pairing and a stable connection let you enjoy your music without interruptions",
    productCategory: "",
    productId: "005",
    productBrand: "Oraimo",
    productColor: "black",
    productPrice: "50",
    productRating: "4",
    productImg: "./../IMAGES/earpod-2-oraimo-black.jpg",
  },
  {
    productName: "Blackview AirBuds ",
    productDesc:
      "Effortless pairing and a stable connection let you enjoy your music without interruptions",
    productCategory: "",
    productId: "006",
    productBrand: "Blackview",
    productColor: "black",
    productPrice: "80",
    productRating: "4",
    productImg: "./../IMAGES/earpod-5-blackview-black.png",
  },
  {
    productName: "AirBuds 4 Pro",
    productDesc:
      "Effortless pairing and a stable connection let you enjoy your music without interruptions",
    productCategory: "",
    productId: "007",
    productBrand: "Blackview",
    productColor: "black",
    productPrice: "200",
    productRating: "5",
    productImg: "./../IMAGES/earpod-6-blackview-black.jpg",
  },
  {
    productName: "Bluetooth 5.0 Headphone",
    productDesc:
      "High-fidelity audio with exceptional clarity and powerful bass for an immersive listening experience.",
    productCategory: "",
    productId: "008",
    productBrand: "Oraimo",
    productColor: "other",
    productPrice: "150",
    productRating: "4",
    productImg: "./../IMAGES/headset-1-oraimo-green.png",
  },
  {
    productName: "Sound Play",
    productDesc:
      " High-fidelity drivers deliver crisp highs, rich mids, and powerful bass for an enjoyable listening experience",
    productCategory: "",
    productId: "009",
    productBrand: "Apple",
    productColor: "white",
    productPrice: "150",
    productRating: "4",
    productImg: "./../IMAGES/headset-2-apple-white.jpg",
  },
  {
    productName: "VT USD-Headset",
    productDesc:
      "Effortless pairing and a stable connection let you enjoy your music without interruptions",
    productCategory: "",
    productId: "010",
    productBrand: "Blackview",
    productColor: "white",
    productPrice: "80",
    productRating: "4",
    productImg: "./../IMAGES/headset-2-blackview-white.jpg",
  },
  {
    productName: "Bluetooth 5.0 Headphone",
    productDesc:
      " High-fidelity drivers deliver crisp highs, rich mids, and powerful bass for an enjoyable listening experience",
    productCategory: "",
    productId: "011",
    productBrand: "Oraimo",
    productColor: "black",
    productPrice: "100",
    productRating: "4",
    productImg: "./../IMAGES/headset-2-oraimo-black.jpeg",
  },
  {
    productName: "Bluetooth 3.0 Headphone",
    productDesc:
      " High-fidelity drivers deliver crisp highs, rich mids, and powerful bass for an enjoyable listening experience",
    productCategory: "",
    productId: "012",
    productBrand: "Blackview",
    productColor: "black",
    productPrice: "100",
    productRating: "4",
    productImg: "./../IMAGES/headset-3-oraimo-black.jpg",
  },
  {
    productName: "Shure Sound Max",
    productDesc:
      " High-fidelity drivers deliver crisp highs, rich mids, and powerful bass for an enjoyable listening experience",
    productCategory: "",
    productId: "013",
    productBrand: "Oraimo",
    productColor: "black",
    productPrice: "100",
    productRating: "4",
    productImg: "./../IMAGES/headset-3-oraimo-black.jpg",
  },
  {
    productName: "Bluetooth 5.0 Studio",
    productDesc:
      " High-fidelity drivers deliver crisp highs, rich mids, and powerful bass for an enjoyable listening experience",
    productCategory: "",
    productId: "014",
    productBrand: "Apple",
    productColor: "other",
    productPrice: "200",
    productRating: "5",
    productImg: "./../IMAGES/headset-4-apple-gold.jpg",
  },
  {
    productName: "Blackview Headphone Pro",
    productDesc:
      " High-fidelity drivers deliver crisp highs, rich mids, and powerful bass for an enjoyable listening experience",
    productCategory: "",
    productId: "015",
    productBrand: "Blackview",
    productColor: "other",
    productPrice: "200",
    productRating: "4",
    productImg: "./../IMAGES/headset-5-blackview-blue.png",
  },

  {
    productName: "Razwer Kitty V2 Pro",
    productDesc:
      " High-fidelity drivers deliver crisp highs, rich mids, and powerful bass for an enjoyable listening experience",
    productCategory: "",
    productId: "016",
    productBrand: "Blackview",
    productColor: "other",
    productPrice: "170",
    productRating: "4",
    productImg: "./../IMAGES/headset_6_blackview_pink.jpeg",
  },

  {
    productName: "Apple Soundcity Max",
    productDesc:
      " High-fidelity drivers deliver crisp highs, rich mids, and powerful bass for an enjoyable listening experience",
    productCategory: "",
    productId: "017",
    productBrand: "Apple",
    productColor: "white",
    productPrice: "180",
    productRating: "5",
    productImg: "./../IMAGES/headset_7_apple_white.jpeg",
  },
  {
    productName: "Blackview Headphone Pro",
    productDesc:
      " High-fidelity drivers deliver crisp highs, rich mids, and powerful bass for an enjoyable listening experience",
    productCategory: "",
    productId: "018",
    productBrand: "Blackview",
    productColor: "other",
    productPrice: "160",
    productRating: "5",
    productImg: "./../IMAGES/headset_9_blackview_gray.jpeg",
  },
];
